// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqBPlny5o1jP122DhY_Yj8UvDe2HfQXO4',
    appId: '1:724083544389:web:86febe86c07bc2dc3f2e2c',
    messagingSenderId: '724083544389',
    projectId: 'projetbinome-a4d5b',
    authDomain: 'projetbinome-a4d5b.firebaseapp.com',
    storageBucket: 'projetbinome-a4d5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsH0MfwKVF0hbvP9wzmXTGquSNR87nt30',
    appId: '1:724083544389:android:1b1846279cc16cae3f2e2c',
    messagingSenderId: '724083544389',
    projectId: 'projetbinome-a4d5b',
    storageBucket: 'projetbinome-a4d5b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-MmeyLlfK3I557opI2N5-fQv8M4KmrNQ',
    appId: '1:724083544389:ios:7022fa15dcc1743d3f2e2c',
    messagingSenderId: '724083544389',
    projectId: 'projetbinome-a4d5b',
    storageBucket: 'projetbinome-a4d5b.firebasestorage.app',
    iosBundleId: 'com.example.projetBinome',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-MmeyLlfK3I557opI2N5-fQv8M4KmrNQ',
    appId: '1:724083544389:ios:7022fa15dcc1743d3f2e2c',
    messagingSenderId: '724083544389',
    projectId: 'projetbinome-a4d5b',
    storageBucket: 'projetbinome-a4d5b.firebasestorage.app',
    iosBundleId: 'com.example.projetBinome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqBPlny5o1jP122DhY_Yj8UvDe2HfQXO4',
    appId: '1:724083544389:web:e577c8613513479b3f2e2c',
    messagingSenderId: '724083544389',
    projectId: 'projetbinome-a4d5b',
    authDomain: 'projetbinome-a4d5b.firebaseapp.com',
    storageBucket: 'projetbinome-a4d5b.firebasestorage.app',
  );
}
